version: '3.7'

services:
  nginx:
    container_name: mynginx
    image: nginx:latest
    networks:
      nginx_net:
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - 80:80

networks:
  nginx_net:
    name: nginx_net